version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile_ubuntu
        tty: true
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
