name: Application CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate Docker
        run: gcloud auth configure-docker asia-east1-docker.pkg.dev --quiet

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test

      - name: Build Docker image
        run: docker build -t asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.REPO_NAME }}/example-app-app:${{ github.sha }} .

      - name: Push Docker image
        run: docker push asia-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ vars.REPO_NAME }}/example-app-app:${{ github.sha }}

#      - name: Deploy to GKE
#        run: |
#          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
#          gcloud container clusters get-credentials $CLUSTER_NAME --region $REGION
#          kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=gcr.io/$PROJECT_ID/$REPO_NAME:$GITHUB_SHA
